### ISSUE TITLE
无法显示qq头像图

### ISSUE THREAD

**Issue by xiaoklee** [erzaozi/neko-status-plugin#10]
插件出来的图一直无法显示qq头像图
删除了插件重新安装也没用
崽是trss，系统win11，用的gitbash挂的
![45BD36DB526CD23AAA2F682531D724CA](https://github.com/user-attachments/assets/b9f622a0-b527-472d-9b36-b5f938073cff)

**Comment by CikeyQi** [comment]
协议端是什么

**Comment by CikeyQi** [comment]
检查你的适配器是否能正常获取到头像，建议将 TRSS-Yunzai 和 LLOneBot 更新到最新版再试
