### ISSUE TITLE
内存信息显示错误

### ISSUE THREAD

**Issue by myueqf** [erzaozi/neko-status-plugin#2]
内存信息显示错误，实际内存占有4.7gb但是显示成了14gb
![Screenshot_20240322_154723](https://github.com/erzaozi/neko-status-plugin/assets/105153381/412db4f4-db3f-46e8-bf10-801fd4275dce)
![Screenshot_20240322_154906](https://github.com/erzaozi/neko-status-plugin/assets/105153381/713c5698-7f05-42be-b078-645a67ac4196)

**Comment by ilworkcn** [comment]
+1

**Comment by CikeyQi** [comment]
确实，我们应该使用 `active` 展示已使用内存而不是 `used`
![image](https://github.com/erzaozi/neko-status-plugin/assets/61369914/3c056a3b-0469-4847-b493-661b731b029d)
