### ISSUE TITLE
#功能建议

### ISSUE THREAD

**Issue by wangxue415** [erzaozi/neko-status-plugin#3]
希望开发者能加入ip地址这样的参数，我的网络存在多个dhcp服务器，我需要经常查看ip地址、网关、dns这些信息

**Comment by CikeyQi** [comment]
这样可能会导致公网IP泄露？毕竟这个状态谁都能调用

**Comment by wangxue415** [comment]
我的想法是，可以设置成可选项。如果开发者有意愿的话，可以做一些简易的远程管理功能

**Comment by CikeyQi** [comment]
[自定义展示](https://github.com/erzaozi/neko-status-plugin?tab=readme-ov-file#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B1%95%E7%A4%BA) 功能已更新
