### ISSUE TITLE
请问能否自定义获取状态的指令呢？

### ISSUE THREAD

**Issue by devil233-ui** [erzaozi/neko-status-plugin#6]
首先感谢大大的制作，猫猫真的很可爱~

但是因为服务器比较菜，经常获取状态要老半天，所以还是希望`#状态`直接得到崽本体的纯文字的输出，需要查看猫猫状态时可以用其他指令获取。刚改配置试了下，不知道是我方法不对还是目前猫猫没有这个功能，并不能实现我的想法……
![image](https://github.com/user-attachments/assets/8c9ee794-c37e-4c34-bb3a-56b3be3f89af)

**Comment by CikeyQi** [comment]
插件暂时无法实现自定义触发命令，如果你想不覆盖原本的 `#状态` 命令，你可以在这里更改触发命令：

https://github.com/erzaozi/neko-status-plugin/blob/c820f6ac2d1ab30dd65cefb88034dcee7dd2956b/apps/Main.js#L19-L21

**Comment by erzaozi** [comment]
以下是可能的两种解决方法
在./config/config/config.yaml
1. 将custom的值改为空数组
2. 删除该文件，重启机器人生成新的配置文件

**Comment by devil233-ui** [comment]
> 以下是可能的两种解决方法 在./config/config/config.yaml
> 
> 1. 将custom的值改为空数组
> 2. 删除该文件，重启机器人生成新的配置文件

已进行了重装，仍无法通过自定义正则触发猫猫，但可以通过无前缀触发，且#状态 不会覆盖云仔
