### ISSUE TITLE
【问题？】模版选择noavatar还是返回了图片

### ISSUE THREAD

**Issue by mengluo04** [erzaozi/neko-status-plugin#8]
![image](https://github.com/user-attachments/assets/63df4163-d1ab-4ee3-9238-d7f3b7db5a9b)
![441f488cca7f1b6a4c020e6475232ac7](https://github.com/user-attachments/assets/3190a9f1-022a-42f0-8757-c5a85f317ce3)

**Comment by CikeyQi** [comment]
noAvatar模板是没有机器人头像，并不是没有底图哦
