### ISSUE TITLE
504 无法获取底图

### ISSUE THREAD

**Issue by devil233-ui** [erzaozi/neko-status-plugin#9]
另外一问，ubuntu的是什么原因无法适配么，我用椰奶也会被识别成arch....
> [02:00:10.701][MARK][指令群(685164226), devil·メイエル(1250226509)][#status][Neko状态(status)][完成4.330秒]
[02:00:08.542][MARK][  TRSSYz  ] [图片生成][neko-status-plugin][12次] 530.35KB 1703ms
  status: 504
      'x-apisix-upstream-status': '504'
    statusText: 'Gateway Time-out',
    status: 504,
      statusMessage: 'Gateway Time-out',
      statusCode: 504,

![Image_1732214912313](https://github.com/user-attachments/assets/62b41aa1-638b-4080-9f5b-3e10cc672b0c)

**Comment by CikeyQi** [comment]
识别成Arch大概率是因为你使用了TRSS脚本部署的

**Comment by CikeyQi** [comment]
底图无法获取请尝试在设置中更换你当前网络环境可用的图片API

**Comment by devil233-ui** [comment]
确实是trss脚本...
原来是代理问题，感谢

**Comment by devil233-ui** [comment]
> 底图无法获取请尝试在设置中更换你当前网络环境可用的图片API

不好意思能否加个代理的配置项呢？找了许多能直连的api质量都比较一般，但是贵插件自带的这个我明明挂着代理也很不稳定，使用其他有代理配置项的插件时代理就基本没出过问题。

**Comment by CikeyQi** [comment]
自行搭建反向代理来代理图片API地址，或者代理软件开启TUN模式全局代理即可，我认为头图没有必要单独设置代理

**Comment by devil233-ui** [comment]
但是这本身就是贵插件相比其他状态插件的亮点所在，能降低门槛是比较好的。反代有点太高估一般用户了（）至于全局代理对于多数不需要代理的插件负面影响较大。
不过刚才翻阅commit历史我找回了原来那个可以直连的api，建议加入配置可选项？

0卡苏打水 ***@***.***> 于 2024年11月30日周六 08:23写道：
